use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'git@git.jiayouxueba.com:gc/XYSpecs.git'

target 'LearnModule_Example' do
  pod 'LearnModule', :path => '../'

  target 'LearnModule_Tests' do
    inherit! :search_paths

    
  end
end
